# Configuration for BVotifier.                    #
# Please use YAML only! NO TABS. 4 spaces instead.#
###################################################
# Thanks, acecheesecr14.                          #
###################################################
bungee:
    # These options are for bungeecord only.
    hostname: '0.0.0.0'
    port: 8192
    debugging: false

    # The below is currently experimental.
    # Enable at your own risk.
    enableThreshold: false
    # The time in milliseconds that an IP has to wait before reconnecting.
    thresholdTime: 200

    # If this is true, then this will be compatable with 1.6 bungeecord.
    StartupOptions:
        v1_6: false
bukkit:
    # These options are for bukkit only.
    debug: false
