name: Votifier
version: ${pom.version}
author: Cory Redmond
description: THIS IS THE BUNGEECORD VOTIFIER.
main: eu.ac3_servers.dev.bvotifier.bukkit.BVotifier
commands:
  votifier:
    description: Toggles debugging.
    usage: /<command>
