name: Votifier
version: 0.1.1
author: acecheesecr14
description: THIS IS THE BUNGEECORD VOTIFIER.
main: eu.ac3_servers.dev.bvotifier.bukkit.BVotifier
commands:
  votifier:
    description: Toggles debugging.
    usage: /<command>
